version: '3.8'
services:
    ssh-client:
        build: .
        restart: always
        volumes:
            - "./private_keys:/private_keys"
            - "./known_hosts:/known_hosts"
        network_mode: host
